### ISSUE TITLE
Not able to pull latest docker image for odd-platform

### ISSUE THREAD

**Issue by preetsindhal** [opendatadiscovery/charts#11]
Error while pulling the image

Kubelet error: Back-off pulling image "ghcr.io/opendatadiscovery/odd-platform:latest"

Simple Docker pull error: 
docker pull ghcr.io/opendatadiscovery/odd-platform
Using default tag: latest
Error response from daemon: manifest unknown

**Comment by DementevNikita** [comment]
hey @preetsindhal!
Thank you for letting us know!

please check again, I've fixed latest tag.
